export const EMPLEADO = [
    {
        "IdEmpleados": 4,
        "IdClientes": 1,
        "Apellido": "Fox",
        "Nombre": "Jonathan",
        "Legajo": "41",
        "CUIL": 20957128832,
        "FechaNacimiento": "28-05-1980",
        "Nacionalidad": "Venezolano",
        "Generos": "Masculino",
        "EstadoCivil": "Casado",
        "TiposDocumentos": "DNI",
        "Documento_Numero": "8317026",
        "Emergencia_Contacto": "Contacto2",
        "Emergencia_Telefono": "5551234",
        "Foto": null,
        "Firma": null,
        "Observaciones": "Obs2",
        "Activo": true,
        "Modif_FYH": "2021-02-19T14:57:46.12",
        "Modif_Usuario": "1",
        "Modif_Ip": "192.168.0.100",
        "Modif_Pc": "JUAN-PC",
        "LstEmpleadosAfip": null,
        "LstEmpleadosBancos": [
            {
                "IdEmpleadosBancos": 2,
                "IdEmpleados": 4,
                "IdBancos": 3,
                "Banco": "Banco Nombre",
                "IdBancosTiposCuenta": 3,
                "TiposCuenta": "Ahorro",
                "Banco_Numero": "3521524/6",
                "Banco_CBU": "002545215246455845",
                "Alias1": "Banco.Loro.Pepe",
                "FechaDesde": "2011-02-19T00:00:00",
                "FechaHasta": "2021-02-19T00:00:00",
                "Observaciones": "obs2",
                "Activo": true,
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "1",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            },
            {
                "IdEmpleadosBancos": 3,
                "IdEmpleados": 4,
                "IdBancos": 3,
                "Banco": "Banco 2",
                "IdBancosTiposCuenta": 3,
                "TiposCuenta": "Corriente",
                "Banco_Numero": "3521524/6",
                "Banco_CBU": "25265485954231",
                "Alias1": "Alias.Alias.Alias",
                "FechaDesde": "2011-02-19T00:00:00",
                "FechaHasta": "2021-02-19T00:00:00",
                "Observaciones": "obs2",
                "Activo": true,
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "1",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            }
        ],
        "LstEmpleadosDomicilios": [
            {
                "IdEmpleadosDomicilios": 3,
                "IdEmpleados": 4,
                "Calle": "Medrano",
                "Numero": "70",
                "Otros": "Entre Mitre y Lezica",
                "CP": "1900",
                "Barrio": "Almagro",
                "Localidad": "CABA",
                "IdProvincias": 1,
                "Provincia": "CABA",
                "FechaDesde": "2011-02-19T00:00:00",
                "FechaHasta": "2021-02-19T00:00:00",
                "Observaciones": "rrrr",
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "1",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            },
            {
                "IdEmpleadosDomicilios": 4,
                "IdEmpleados": 4,
                "Calle": "Corrientes",
                "Numero": "3710",
                "Otros": "Esquina Mario Bravo",
                "CP": "1900",
                "Barrio": "Almagro",
                "Localidad": "CABA",
                "IdProvincias": 1,
                "Provincia": "CABA",
                "FechaDesde": "2011-02-19T00:00:00",
                "FechaHasta": "2021-02-19T00:00:00",
                "Observaciones": "rrrr",
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "1",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            },
        ],
        "LstEmpleadosEmails": [
            {
                "IdEmpleadosEmails": 2,
                "IdEmpleados": 4,
                "Email": "mail@mail.com",
                "Preferido": true,
                "Activo": true,
                "Observaciones": "obs2",
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "2021-02-19 14:57:46.120",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            }
        ],
        "LstEmpleadosHistorial": [
            {
                "IdEmpleados_Historiales": 2,
                "IdCliente": 1,
                "IdEmpleado": 4,
                "Fecha_Desde": "2021-02-19T00:00:00",
                "Fecha_Hasta": "2021-02-19T00:00:00",
                "Modif_FYH": "2021-02-19 14:57:46.120",
                "Modif_Usuario": "1",
                "Modif_Ip": "192.168.0.100",
                "Modif_Pc": "JUAN-PC"
            }
        ],
        "LstEmpleadosObraSocial": [],
        "LstEmpleadosPuestos": [
            {
                "IdEmpleadosPuestos": 3,
                "IdEmpleados": 4,
                "IdSectores": 4,
                "FechaDesde": "2021-02-19T00:00:00",
                "FechaHasta": "2021-02-19T00:00:00",
                "Observaciones": "gggg",
                "Modif_FYH": "2021-02-19T14:57:46.12",
                "Modif_Usuario": "1",
                "Modif_Ip": "1",
                "Modif_Pc": "1"
            }
        ],
        "LstEmpleadosSectores": [],
        "LstEmpleadosSindicatos": [],
        "LstEmpleadosTelefonos": [],
        "LstEmpleadosUbicaciones": [],
    }
]